// Generated by CoffeeScript 1.7.1

/*
deepscan
v0.12345
asifjahmed
 */

(function() {
  var App, PlaySound, clientSelected, doubleDigit, renderGrids, ssidSelected, timeConverter, toggleRecentOnly;

  App = {};

  $(document).ready(function() {
    App.socket = io.connect;
    App.socket.on('ssid', App.ssid);
    App.socket.on('client', App.client);
    App.socket.on('time', App.time);
    App.socket.on('packetrate', App.packetrate);
    return renderGrids();
  });

  timeConverter = function(unixtime) {
    var a, hour, min, sec;
    a = new Date(unixtime * 1000);
    hour = a.getHours();
    min = a.getMinutes();
    sec = a.getSeconds();
    return "" + hour + ":" + (doubleDigit(min)) + ":" + (doubleDigit(sec));
  };

  doubleDigit = function(n) {
    if (n > 9) {
      return "";
    } else {
      return "0" + n;
    }
  };

  App.ssid = function(data) {
    var ssidexists, _ref, _ref1;
    if ($('#ssidalert').val() === data.mac) {
      if ($('#enablessidsound').prop('checked')) {
        PlaySound('sound1');
        $("#ssidalertflasher").fadeIn(50).fadeOut(50);
      }
    }
    ssidexists = $('#ssidgrid').getCell(data.mac, 'mac');
    if (ssidexists) {
      return $('#ssidgrid').setRowData(data.mac, {
        ssid: (_ref = data.ssid.trim() === '') != null ? _ref : {
          '- hidden ssid -': data.ssid
        },
        mac: data.mac,
        type: data.type,
        lasttime: timeConverter(data.lasttime),
        manuf: data.manuf,
        channel: data.channel,
        signal_dbm: data.signal_dbm
      });
    } else {
      return $('#ssidgrid').addRowData(data.mac, {
        ssid: (_ref1 = data.ssid.trim() === '') != null ? _ref1 : {
          '- hidden ssid -': data.ssid
        },
        mac: data.mac,
        type: data.type,
        lasttime: timeConverter(data.lasttime),
        manuf: data.manuf,
        channel: data.channel,
        signal_dbm: data.signal_dbm
      });
    }
  };

  App.client = function(data) {
    var clientexists, _ref, _ref1, _ref2, _ref3;
    if ($('#clientalert').val() === data.mac) {
      if ($('#enableclientsound').prop('checked')) {
        PlaySound('sound1');
        $("#clientalertflasher").fadeIn(50).fadeOut(50);
      }
    }
    clientexists = $('#clientgrid').getCell(data.mac, 'mac');
    if (clientexists) {
      return $('#clientgrid').setRowData(data.mac, {
        name: data.name,
        bssid: (_ref = data.bssid === data.mac) != null ? _ref : {
          '- self -': data.bssid
        },
        bssidsrc: (_ref1 = $('#ssidgrid').getRowData(data.bssid).ssid === void 0) != null ? _ref1 : {
          '': $('#ssidgrid').getRowData(data.bssid).ssid
        },
        manuf: data.manuf,
        mac: data.mac,
        type: data.type,
        lasttime: timeConverter(data.lasttime),
        signal_dbm: data.signal_dbm,
        datasize: data.datasize,
        ppm: data.ppm,
        username: data.username,
        channel: data.channel
      });
    } else {
      return $('#clientgrid').addRowData(data.mac, {
        name: data.name,
        bssid: (_ref2 = data.bssid === data.mac) != null ? _ref2 : {
          '- self -': data.bssid
        },
        bssidsrc: (_ref3 = $('#ssidgrid').getRowData(data.bssid).ssid === void 0) != null ? _ref3 : {
          '': $('#ssidgrid').getRowData(data.bssid).ssid
        },
        manuf: data.manuf,
        mac: data.mac,
        type: data.type,
        lasttime: timeConverter(data.lasttime),
        signal_dbm: data.signal_dbm,
        datasize: data.datasize,
        ppm: data.ppm,
        username: data.username,
        channel: data.channel
      });
    }
  };

  App.time = function(data) {
    return $('#txtTime').val(timeConverter(data.timesec));
  };

  App.packetrate = function(data) {
    if ($('#clientgrid').getRowData(data.mac) !== void 0) {
      if (data.ppm === 0 && recentonly) {
        return $('#clientgrid').delRowData(data.mac);
      } else {
        return $('#clientgrid').setCell(data.mac, 'ppm', data.ppm);
      }
    }
  };

  renderGrids = function() {
    $("#ssidgrid").jqGrid({
      datatype: "local",
      width: 650,
      height: 600,
      colNames: ["ssid", "mac", "manufacturer", "type", "last seen", "channel", "dBm"],
      colModel: [
        {
          name: "ssid",
          index: "ssid",
          sorttype: "text",
          width: 90
        }, {
          name: "mac",
          index: "mac",
          sorttype: "text",
          key: true,
          width: 65
        }, {
          name: "manuf",
          index: "manuf",
          sorttype: "text",
          width: 60
        }, {
          name: "type",
          index: "type",
          sorttype: "int",
          width: 25
        }, {
          name: "lasttime",
          index: "lasttime",
          sorttype: "time",
          width: 40
        }, {
          name: "channel",
          index: "channel",
          sorttype: "int",
          width: 40
        }, {
          name: "signal_dbm",
          index: "signal_dbm",
          sorttype: "int",
          width: 20
        }
      ],
      pager: "#ssidpager",
      rowNum: 200,
      sortname: "lasttime",
      viewrecords: true,
      sortorder: "desc",
      caption: "ssid",
      onSelectRow: ssidSelected,
      beforeSelectRow: function(rowid) {
        if ($(this).jqGrid("getGridParam", "selrow") === rowid) {
          $(this).jqGrid("resetSelection");
          $("#ssidalert").val("");
          return false;
        } else {
          return true;
        }
      }
    });
    $("#ssidgrid").jqGrid("navGrid", "#ssidpager", {
      del: false,
      add: false,
      edit: false,
      search: false
    });
    $("#ssidgrid").jqGrid("filterToolbar", {
      stringResult: true,
      searchOnEnter: false
    });
    $("#clientgrid").jqGrid({
      datatype: "local",
      width: 900,
      height: 600,
      colNames: ["name", "mac", "manufacturer", "bssid", "bssid src", "type", "last seen", "ppm", "interface", "channel", "dBm", "data size"],
      colModel: [
        {
          name: "name",
          index: "name",
          sorttype: "text",
          width: 60
        }, {
          name: "mac",
          index: "mac",
          sorttype: "text",
          key: true,
          width: 60
        }, {
          name: "manuf",
          index: "manuf",
          sorttype: "text",
          width: 60
        }, {
          name: "bssid",
          index: "bssid",
          sorttype: "text",
          width: 60
        }, {
          name: "bssidsrc",
          index: "bssidsrc",
          sorttype: "text",
          width: 90
        }, {
          name: "type",
          index: "type",
          sorttype: "int",
          width: 20
        }, {
          name: "lasttime",
          index: "lasttime",
          sorttype: "time",
          width: 35
        }, {
          name: "ppm",
          index: "ppm",
          sorttype: "int",
          width: 25
        }, {
          name: "username",
          index: "username",
          sorttype: "text",
          width: 30
        }, {
          name: "channel",
          index: "channel",
          sorttype: "int",
          width: 30
        }, {
          name: "signal_dbm",
          index: "signal_dbm",
          sorttype: "int",
          width: 20
        }, {
          name: "datasize",
          index: "datasize",
          sorttype: "int",
          width: 30
        }
      ],
      pager: "#clientpager",
      rowNum: 200,
      sortname: "lasttime",
      viewrecords: true,
      sortorder: "desc",
      caption: "client",
      onSelectRow: clientSelected,
      beforeSelectRow: function(rowid) {
        if ($(this).jqGrid("getGridParam", "selrow") === rowid) {
          $(this).jqGrid("resetSelection");
          $("#clientalert").val("");
          return false;
        } else {
          return true;
        }
      }
    });
    $("#clientgrid").jqGrid("navGrid", "#clientpager", {
      del: false,
      add: false,
      edit: false,
      search: false
    });
    return $("#clientgrid").jqGrid("filterToolbar", {
      stringResult: true,
      searchOnEnter: false
    });
  };

  ssidSelected = function(obj) {
    $('#clientgrid').resetSelection();
    return $('#ssidalert').val(obj);
  };

  clientSelected = function(obj) {
    $('#ssidgrid').resetSelection();
    return $('#clientalert').val(obj);
  };

  PlaySound = function(sound) {
    return $("#" + sound)[0].play();
  };

  toggleRecentOnly = function() {
    var data, mac, recentonly, x;
    recentonly = $("#enablerecentonly").prop('checked');
    if (recentonly) {
      data = $('#clientgrid').getDataIDs();
      x = 0;
      while (x < data.length) {
        mac = data[x];
        if ($('#clientgrid').getCell(mac, 'ppm') === 0) {
          $('#clientgrid').delRowData(mac);
        }
        x++;
      }
      return data.length = 0;
    }
  };

}).call(this);
